services:
  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

    depends_on:
      backend:
        condition: service_started

  backend:
    container_name: backend
    build: 
      context: ./chartapi
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - DJANGO_SETTINGS_MODULE=chartapi.settings
